version: 2

sources:
  - name: file_system
    database: DL_NERDS
    schema: bronze
    tables:
      - name: country_raw
      - name: customer_raw
      - name: product_raw
      - name: sales_raw
      # Adding Freshness to sources.yml
        config:
          loaded_at_field: updated_at
          freshness:
           warn_after: {count: 12, period: hour}
           error_after: {count: 2, period: day}