version: 2

sources:
  - name: file_system
    database: DL_NERDS
    schema: bronze
    tables:
      - name: country_raw
      - name: customer_raw
      - name: product_raw
      - name: sales_raw
